- name: 创建目录
  file: path={{tmp_path}} state=directory owner=root group=root
  
- name: 上传修复脚本
  synchronize: mode=push src={{fix_path}}/{{ip}}_os_fix.sh dest={{tmp_path}}

- name: 增加执行权限({{ip}}_os_fix.sh)
  command: sudo su - root -c "chmod +x {{tmp_path}}/{{ip}}_os_fix.sh"
  
#- name: 执行修复脚本({{ip}}_os_fix.sh)
#  command: sudo su - root -c "bash {{tmp_path}}/{{ip}}_os_fix.sh"
  
#- name: 获取修复日志
#  synchronize: mode=pull src=/tmp/{{ip}}_os_fix.log dest={{log_path}}
